#!/usr/bin/env bash
# This script displays the content of the current directory in list format
# Only displays the part of the name after the first dash

mylist=$(ls)

for a in $mylist; do
  echo "$a" | cut -d '-' -f2
done
